export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_STYLES = 'GET_PRODUCT_STYLES';
export const GET_CURRENT_STYLE = 'GET_CURRENT_STYLE';
export const ADD_CART_ITEMS = 'ADD_CART_ITEMS';
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const GET_CART_DETAILS = 'GET_CART_DETAILS';
//